include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DynamicIslandLSColor16Prefs
DynamicIslandLSColor16Prefs_FILES = DILSRootListController.m
DynamicIslandLSColor16Prefs_FRAMEWORKS = UIKit Foundation CoreFoundation
DynamicIslandLSColor16Prefs_PRIVATE_FRAMEWORKS = Preferences
DynamicIslandLSColor16Prefs_CFLAGS = -fobjc-arc -Wall -Wextra -Wno-unused-parameter
DynamicIslandLSColor16Prefs_INSTALL_PATH = /Library/PreferenceBundles
DynamicIslandLSColor16Prefs_RESOURCE_DIRS = Resources

include $(THEOS_MAKE_PATH)/bundle.mk
